---
- name: Install apache
  hosts: localhost
  become: true

  tasks:
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - httpd-tools

    - name: Make sure a service is running
      systemd:
        state: started
        name: httpd
